apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      service: vote
      # app: vote
  template:
    metadata:
      labels:
        service: vote
        # app: vote
    spec:
      containers:
        - image: ghcr.io/subicura/voting/vote:latest
          name: vote
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
              protocol: TCP

--- 
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 31000
  selector:
    service: vote
    # app: vote
    # tier: app